/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'haochen' at '1/1/16 7:44 PM' with Gradle 2.8
 *
 * @author haochen, @date 1/1/16 7:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
